import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import Swal from 'sweetalert2';
import { ValidatorsService } from '../../../shared/services/validators.service';

declare var $:any;

@Component({
  selector: 'distrital-actas',
  templateUrl: './actas.component.html',
  styleUrl: './actas.component.css'
})
export class ActasComponent implements OnInit {
  private fb = inject(FormBuilder);
  private validatorsService = inject(ValidatorsService);


  public selectForm = this.fb.group({
    id_demarcacion:['',[Validators.required]],
    id_seccion:['',[Validators.required]],
    tipo_casilla:['',[Validators.required]],
    id_tipo_eleccion:['',[Validators.required]],
  });

  public formGroup1 = this.fb.group({
    votos_cand_1:['',[Validators.required]],
    votos_cand_2:['',[Validators.required]],
    votos_cand_3:['',[Validators.required]]
  });

  public formGroup2 = this.fb.group({
    votos_cand_4:['',[Validators.required]]
  });

  public formGroup3 = this.fb.group({
    votos_cand_5:['',[Validators.required]]
  });

    // votos_cand_6:['',[Validators.required]],
    // votos_cand_7:['',[Validators.required]],
    // votos_cand_8:['',[Validators.required]],
    // votos_cand_9:['',[Validators.required]],
    // votos_cand_10:['',[Validators.required]],
    // votos_cand_11:['',[Validators.required]],
    // votos_cand_12:['',[Validators.required]],
    // votos_cand_13:['',[Validators.required]],
    // votos_cand_14:['',[Validators.required]],
    // votos_cand_15:['',[Validators.required]],
    // votos_cand_16:['',[Validators.required]],
    // votos_cand_17:['',[Validators.required]],
    // votos_cand_18:['',[Validators.required]],
    // votos_cand_19:['',[Validators.required]],
    // votos_cand_20:['',[Validators.required]],
    // votos_cand_21:['',[Validators.required]],
    // votos_cand_22:['',[Validators.required]],
    // votos_cand_23:['',[Validators.required]],
    // votos_cand_24:['',[Validators.required]],
    // votos_cand_25:['',[Validators.required]],
    // votos_cand_26:['',[Validators.required]],
    // votos_cand_27:['',[Validators.required]],
    // votos_cand_28:['',[Validators.required]],
    // votos_cand_29:['',[Validators.required]],
    // votos_cand_30:['',[Validators.required]],
    // votos_cand_31:['',[Validators.required]],
    // votos_cand_32:['',[Validators.required]],
    // votos_cand_33:['',[Validators.required]],
    // votos_cand_34:['',[Validators.required]],
    // votos_cand_35:['',[Validators.required]],
    // votos_cand_36:['',[Validators.required]],
    // votos_cand_37:['',[Validators.required]],
    // votos_cand_38:['',[Validators.required]],
    // votos_cand_39:['',[Validators.required]],
    // votos_cand_40:['',[Validators.required]],
    // votos_cand_41:['',[Validators.required]],
    // votos_cand_42:['',[Validators.required]],
    // votos_cand_43:['',[Validators.required]],
    // votos_cand_44:['',[Validators.required]],
    // votos_cand_45:['',[Validators.required]],
    // votos_cand_46:['',[Validators.required]],
    // votos_cand_47:['',[Validators.required]],
    // votos_cand_48:['',[Validators.required]],
    // votos_cand_49:['',[Validators.required]],
    // votos_cand_50:['',[Validators.required]],
    // votos_cand_51:['',[Validators.required]],
    // votos_cand_52:['',[Validators.required]],
    // votos_cand_53:['',[Validators.required]],
    // votos_cand_54:['',[Validators.required]],
    // votos_cand_55:['',[Validators.required]],
    // votos_cand_56:['',[Validators.required]],
    // votos_cand_57:['',[Validators.required]],
    // votos_cand_58:['',[Validators.required]],
    // votos_cand_59:['',[Validators.required]],
    // votos_cand_60:['',[Validators.required]],
    // votos_cand_61:['',[Validators.required]],
    // votos_cand_62:['',[Validators.required]],
    // votos_cand_63:['',[Validators.required]],
    // votos_cand_64:['',[Validators.required]],
    // votos_cand_65:['',[Validators.required]],
    // votos_cand_66:['',[Validators.required]],
    // votos_cand_67:['',[Validators.required]],
    // votos_cand_68:['',[Validators.required]],
    // votos_cand_69:['',[Validators.required]],
    // votos_cand_70:['',[Validators.required]],
    // votos_cand_71:['',[Validators.required]],
    // votos_cand_72:['',[Validators.required]],
    // votos_cand_73:['',[Validators.required]],
    // votos_cand_74:['',[Validators.required]],
    // votos_cand_75:['',[Validators.required]],
    // votos_cand_76:['',[Validators.required]],
    // votos_cand_77:['',[Validators.required]],
    // votos_cand_78:['',[Validators.required]],
    // votos_cand_79:['',[Validators.required]],
    // votos_cand_80:['',[Validators.required]],
    // votos_cand_81:['',[Validators.required]],
    // votos_cand_82:['',[Validators.required]],
    // votos_cand_83:['',[Validators.required]],
    // votos_cand_84:['',[Validators.required]],
    // votos_cand_85:['',[Validators.required]],
    // votos_cand_86:['',[Validators.required]],
    // votos_cand_87:['',[Validators.required]],
    // votos_cand_88:['',[Validators.required]],
    // votos_cand_89:['',[Validators.required]],
    // votos_cand_90:['',[Validators.required]],
    // votos_cand_91:['',[Validators.required]],
    // votos_cand_92:['',[Validators.required]],
    // votos_cand_93:['',[Validators.required]],
    // votos_cand_94:['',[Validators.required]],
    // votos_cand_95:['',[Validators.required]],
    // votos_cand_96:['',[Validators.required]],
    // votos_cand_97:['',[Validators.required]],
    // votos_cand_98:['',[Validators.required]],
    // votos_cand_99:['',[Validators.required]],
    // votos_cand_100:['',[Validators.required]],
    // votos_cand_101:['',[Validators.required]],
    // votos_cand_102:['',[Validators.required]],
    // votos_cand_103:['',[Validators.required]],
    // votos_cand_104:['',[Validators.required]],
    // votos_cand_105:['',[Validators.required]],
    // votos_cand_106:['',[Validators.required]],
    // votos_cand_107:['',[Validators.required]],
    // votos_cand_108:['',[Validators.required]],
    // votos_cand_109:['',[Validators.required]],
    // votos_cand_110:['',[Validators.required]],
    // votos_cand_111:['',[Validators.required]],
    // votos_cand_112:['',[Validators.required]],
    // votos_cand_113:['',[Validators.required]],
    // votos_cand_114:['',[Validators.required]],
    // votos_cand_115:['',[Validators.required]],
    // votos_cand_116:['',[Validators.required]],
    // votos_cand_117:['',[Validators.required]],
    // votos_cand_118:['',[Validators.required]],
    // votos_cand_119:['',[Validators.required]],
    // votos_cand_120:['',[Validators.required]],
    // votos_cand_121:['',[Validators.required]],
    // votos_cand_122:['',[Validators.required]],
    // votos_cand_123:['',[Validators.required]],
    // votos_cand_124:['',[Validators.required]],
    // votos_cand_125:['',[Validators.required]],
    // votos_cand_126:['',[Validators.required]],
    // votos_cand_127:['',[Validators.required]],
    // votos_cand_128:['',[Validators.required]],
    // votos_cand_129:['',[Validators.required]],
    // votos_cand_130:['',[Validators.required]],
    // votos_cand_131:['',[Validators.required]],
    // votos_cand_132:['',[Validators.required]],
    // votos_cand_133:['',[Validators.required]],
    // votos_cand_134:['',[Validators.required]],
    // votos_cand_135:['',[Validators.required]],
    // votos_cand_136:['',[Validators.required]],
    // votos_cand_137:['',[Validators.required]],
    // votos_cand_138:['',[Validators.required]],
    // votos_cand_139:['',[Validators.required]],
    // votos_cand_140:['',[Validators.required]],
    // votos_cand_141:['',[Validators.required]],
    // votos_cand_142:['',[Validators.required]],
    // votos_cand_143:['',[Validators.required]],
    // votos_cand_144:['',[Validators.required]],
    // votos_cand_145:['',[Validators.required]],
    // votos_cand_146:['',[Validators.required]],
    // votos_cand_147:['',[Validators.required]],
    // votos_cand_148:['',[Validators.required]],
    // votos_cand_149:['',[Validators.required]],
    // votos_cand_150:['',[Validators.required]],
    // votos_cand_151:['',[Validators.required]],
    // votos_cand_152:['',[Validators.required]],
    // votos_cand_153:['',[Validators.required]],
    // votos_cand_154:['',[Validators.required]],
    // votos_cand_155:['',[Validators.required]],
    // votos_cand_156:['',[Validators.required]],
    // votos_cand_157:['',[Validators.required]],
    // votos_cand_158:['',[Validators.required]],
    // votos_cand_159:['',[Validators.required]],
    // votos_cand_160:['',[Validators.required]],
    // votos_cand_161:['',[Validators.required]],
    // votos_cand_162:['',[Validators.required]],
    // votos_cand_163:['',[Validators.required]],
    // votos_cand_164:['',[Validators.required]],
    // votos_cand_165:['',[Validators.required]],
    // votos_cand_166:['',[Validators.required]],
    // votos_cand_167:['',[Validators.required]],
    // votos_cand_168:['',[Validators.required]],
    // votos_cand_169:['',[Validators.required]],
    // votos_cand_170:['',[Validators.required]],
    // votos_cand_171:['',[Validators.required]],
    // votos_cand_172:['',[Validators.required]],
    // votos_cand_173:['',[Validators.required]],
    // votos_cand_174:['',[Validators.required]],
    // votos_cand_175:['',[Validators.required]],
    // votos_cand_176:['',[Validators.required]],
    // votos_cand_177:['',[Validators.required]],
    // votos_cand_178:['',[Validators.required]],
    // votos_cand_179:['',[Validators.required]],
    // votos_cand_180:['',[Validators.required]],
    // votos_cand_181:['',[Validators.required]],
    // votos_cand_182:['',[Validators.required]],
    // votos_cand_183:['',[Validators.required]],
    // votos_cand_184:['',[Validators.required]],
    // votos_cand_185:['',[Validators.required]],
    // votos_cand_186:['',[Validators.required]],
    // votos_cand_187:['',[Validators.required]],
    // votos_cand_188:['',[Validators.required]],
    // votos_cand_189:['',[Validators.required]],
    // votos_cand_190:['',[Validators.required]],
    // votos_cand_191:['',[Validators.required]],
    // votos_cand_192:['',[Validators.required]],
    // votos_cand_193:['',[Validators.required]],
    // votos_cand_194:['',[Validators.required]],
    // votos_cand_195:['',[Validators.required]],
    // votos_cand_196:['',[Validators.required]],
    // votos_cand_197:['',[Validators.required]],
    // votos_cand_198:['',[Validators.required]],
    // votos_cand_199:['',[Validators.required]],
    // votos_cand_200:['',[Validators.required]],
    // votos_cand_201:['',[Validators.required]],
    // votos_cand_202:['',[Validators.required]],
    // votos_cand_203:['',[Validators.required]],
    // votos_cand_204:['',[Validators.required]],
    // votos_cand_205:['',[Validators.required]],
    // votos_cand_206:['',[Validators.required]],
    // votos_cand_207:['',[Validators.required]],
    // votos_cand_208:['',[Validators.required]],
    // votos_cand_209:['',[Validators.required]],
    // votos_cand_210:['',[Validators.required]],
    // votos_cand_211:['',[Validators.required]],
    // votos_cand_212:['',[Validators.required]],
    // votos_cand_213:['',[Validators.required]],
    // votos_cand_214:['',[Validators.required]],
    // votos_cand_215:['',[Validators.required]],
    // votos_cand_216:['',[Validators.required]],
    // votos_cand_217:['',[Validators.required]],
    // votos_cand_218:['',[Validators.required]],
    // votos_cand_219:['',[Validators.required]],
    // votos_cand_220:['',[Validators.required]],
    // votos_cand_221:['',[Validators.required]],
    // votos_cand_222:['',[Validators.required]],
    // votos_cand_223:['',[Validators.required]],
    // votos_cand_224:['',[Validators.required]],
    // votos_cand_225:['',[Validators.required]],
    // votos_cand_226:['',[Validators.required]],
    // votos_cand_227:['',[Validators.required]],
    // votos_cand_228:['',[Validators.required]],
    // votos_cand_229:['',[Validators.required]],
    // votos_cand_230:['',[Validators.required]],
    // votos_cand_231:['',[Validators.required]],
    // votos_cand_232:['',[Validators.required]],
    // votos_cand_233:['',[Validators.required]],
    // votos_cand_234:['',[Validators.required]],
    // votos_cand_235:['',[Validators.required]],
    // votos_cand_236:['',[Validators.required]],
    // votos_cand_237:['',[Validators.required]],
    // votos_cand_238:['',[Validators.required]],
    // votos_cand_239:['',[Validators.required]],
    // votos_cand_240:['',[Validators.required]],
    // votos_cand_241:['',[Validators.required]],
    // votos_cand_242:['',[Validators.required]],
    // votos_cand_243:['',[Validators.required]],
    // votos_cand_244:['',[Validators.required]],
    // votos_cand_245:['',[Validators.required]],
    // votos_cand_246:['',[Validators.required]],
    // votos_cand_247:['',[Validators.required]],
    // votos_cand_248:['',[Validators.required]],
    // votos_cand_249:['',[Validators.required]],
    // votos_cand_250:['',[Validators.required]],
    // votos_cand_251:['',[Validators.required]],
    // votos_cand_252:['',[Validators.required]],
    // votos_cand_253:['',[Validators.required]],
    // votos_cand_254:['',[Validators.required]],
    // votos_cand_255:['',[Validators.required]],
    // votos_cand_256:['',[Validators.required]],
    // votos_cand_257:['',[Validators.required]],
    // votos_cand_258:['',[Validators.required]],
    // votos_cand_259:['',[Validators.required]],
    // votos_cand_260:['',[Validators.required]],
    // votos_cand_261:['',[Validators.required]],
    // votos_cand_262:['',[Validators.required]],
    // votos_cand_263:['',[Validators.required]],
    // votos_cand_264:['',[Validators.required]],
    // votos_cand_265:['',[Validators.required]],
    // votos_cand_266:['',[Validators.required]],
    // votos_cand_267:['',[Validators.required]],
    // votos_cand_268:['',[Validators.required]],
    // votos_cand_269:['',[Validators.required]],
    // votos_cand_270:['',[Validators.required]],
    // votos_cand_271:['',[Validators.required]],
    // votos_cand_272:['',[Validators.required]],
    // votos_cand_273:['',[Validators.required]],
    // votos_cand_274:['',[Validators.required]],
    // votos_cand_275:['',[Validators.required]],
    // votos_cand_276:['',[Validators.required]],
    // votos_cand_277:['',[Validators.required]],
    // votos_cand_278:['',[Validators.required]],
    // votos_cand_279:['',[Validators.required]],
    // votos_cand_280:['',[Validators.required]],
    // votos_cand_281:['',[Validators.required]],
    // votos_cand_282:['',[Validators.required]],
    // votos_cand_283:['',[Validators.required]],
    // votos_cand_284:['',[Validators.required]],
    // votos_cand_285:['',[Validators.required]],
    // votos_cand_286:['',[Validators.required]],
    // votos_cand_287:['',[Validators.required]],
    // votos_cand_288:['',[Validators.required]],
    // votos_cand_289:['',[Validators.required]],
    // votos_cand_290:['',[Validators.required]],
    // votos_cand_291:['',[Validators.required]],
    // votos_cand_292:['',[Validators.required]],
    // votos_cand_293:['',[Validators.required]],
    // votos_cand_294:['',[Validators.required]],
    // votos_cand_295:['',[Validators.required]],
    // votos_cand_296:['',[Validators.required]],
    // votos_cand_297:['',[Validators.required]],
    // votos_cand_298:['',[Validators.required]],
    // votos_cand_299:['',[Validators.required]],
    // votos_cand_300:['',[Validators.required]],
    // votos_cand_301:['',[Validators.required]],
    // votos_cand_302:['',[Validators.required]],
    // votos_cand_303:['',[Validators.required]],
    // votos_cand_304:['',[Validators.required]],
    // votos_cand_305:['',[Validators.required]],
    // votos_cand_306:['',[Validators.required]],
    // votos_cand_307:['',[Validators.required]],
    // votos_cand_308:['',[Validators.required]],
    // votos_cand_309:['',[Validators.required]],
    // votos_cand_310:['',[Validators.required]],
    // votos_cand_311:['',[Validators.required]],
    // votos_cand_312:['',[Validators.required]],
    // votos_cand_313:['',[Validators.required]],
    // votos_cand_314:['',[Validators.required]],
    // votos_cand_315:['',[Validators.required]],
    // votos_cand_316:['',[Validators.required]],
    // votos_cand_317:['',[Validators.required]],
    // votos_cand_318:['',[Validators.required]],
    // votos_cand_319:['',[Validators.required]],
    // votos_cand_320:['',[Validators.required]],
    // votos_cand_321:['',[Validators.required]],
    // votos_cand_322:['',[Validators.required]],
    // votos_cand_323:['',[Validators.required]],
    // votos_cand_324:['',[Validators.required]],
    // votos_cand_325:['',[Validators.required]],
    // votos_cand_326:['',[Validators.required]],
    // votos_cand_327:['',[Validators.required]],
    // votos_cand_328:['',[Validators.required]],
    // votos_cand_329:['',[Validators.required]],
    // votos_cand_330:['',[Validators.required]],
    // votos_cand_331:['',[Validators.required]],
    // votos_cand_332:['',[Validators.required]],
    // votos_cand_333:['',[Validators.required]],
    // votos_cand_334:['',[Validators.required]],
    // votos_cand_335:['',[Validators.required]],
    // votos_cand_336:['',[Validators.required]],
    // votos_cand_337:['',[Validators.required]],
    // votos_cand_338:['',[Validators.required]],
    // votos_cand_339:['',[Validators.required]],
    // votos_cand_340:['',[Validators.required]],
    // votos_cand_341:['',[Validators.required]],
    // votos_cand_342:['',[Validators.required]],
    // votos_cand_343:['',[Validators.required]],
    // votos_cand_344:['',[Validators.required]],
    // votos_cand_345:['',[Validators.required]],
    // votos_cand_346:['',[Validators.required]],
    // votos_cand_347:['',[Validators.required]],
    // votos_cand_348:['',[Validators.required]],
    // votos_cand_349:['',[Validators.required]],
    // votos_cand_350:['',[Validators.required]],
    // votos_cand_351:['',[Validators.required]],
    // votos_cand_352:['',[Validators.required]],
    // votos_cand_353:['',[Validators.required]],
    // votos_cand_354:['',[Validators.required]],
    // votos_cand_355:['',[Validators.required]],
    // votos_cand_356:['',[Validators.required]],
    // votos_cand_357:['',[Validators.required]],
    // votos_cand_358:['',[Validators.required]],
    // votos_cand_359:['',[Validators.required]],
    // votos_cand_360:['',[Validators.required]],
    // votos_cand_361:['',[Validators.required]],
    // votos_cand_362:['',[Validators.required]],
    // votos_cand_363:['',[Validators.required]],
    // votos_cand_364:['',[Validators.required]],
    // votos_cand_365:['',[Validators.required]],
    // votos_cand_366:['',[Validators.required]],
    // votos_cand_367:['',[Validators.required]],
    // votos_cand_368:['',[Validators.required]],
    // votos_cand_369:['',[Validators.required]],
    // votos_cand_370:['',[Validators.required]],
    // votos_cand_371:['',[Validators.required]],
    // votos_cand_372:['',[Validators.required]],
    // votos_cand_373:['',[Validators.required]],
    // votos_cand_374:['',[Validators.required]],
    // votos_cand_375:['',[Validators.required]],
    // votos_cand_376:['',[Validators.required]],
    // votos_cand_377:['',[Validators.required]],
    // votos_cand_378:['',[Validators.required]],
    // votos_cand_379:['',[Validators.required]],
    // votos_cand_380:['',[Validators.required]],
    // votos_cand_381:['',[Validators.required]],
    // votos_cand_382:['',[Validators.required]],
    // votos_cand_383:['',[Validators.required]],
    // votos_cand_384:['',[Validators.required]],
    // votos_cand_385:['',[Validators.required]],
    // votos_cand_386:['',[Validators.required]],
    // votos_cand_387:['',[Validators.required]],
    // votos_cand_388:['',[Validators.required]],
    // votos_cand_389:['',[Validators.required]],
    // votos_cand_390:['',[Validators.required]],
    // votos_cand_391:['',[Validators.required]],
    // votos_cand_392:['',[Validators.required]],
    // votos_cand_393:['',[Validators.required]],
    // votos_cand_394:['',[Validators.required]],
    // votos_cand_395:['',[Validators.required]],
    // votos_cand_396:['',[Validators.required]],
    // votos_cand_397:['',[Validators.required]],
    // votos_cand_398:['',[Validators.required]],
    // votos_cand_399:['',[Validators.required]],
    // votos_cand_400:['',[Validators.required]],
    // votos_cand_401:['',[Validators.required]],
    // votos_cand_402:['',[Validators.required]],
    // votos_cand_403:['',[Validators.required]],
    // votos_cand_404:['',[Validators.required]],
    // votos_cand_405:['',[Validators.required]],
    // votos_cand_406:['',[Validators.required]],
    // votos_cand_407:['',[Validators.required]],
    // votos_cand_408:['',[Validators.required]],
    // votos_cand_409:['',[Validators.required]],
    // votos_cand_410:['',[Validators.required]],
    // votos_cand_411:['',[Validators.required]],
    // votos_cand_412:['',[Validators.required]],
    // votos_cand_413:['',[Validators.required]],
    // votos_cand_414:['',[Validators.required]],
    // votos_cand_415:['',[Validators.required]],
    // votos_cand_416:['',[Validators.required]],
    // votos_cand_417:['',[Validators.required]],
    // votos_cand_418:['',[Validators.required]],
    // votos_cand_419:['',[Validators.required]],
    // votos_cand_420:['',[Validators.required]],
    // votos_cand_421:['',[Validators.required]],
    // votos_cand_422:['',[Validators.required]],
    // votos_cand_423:['',[Validators.required]],
    // votos_cand_424:['',[Validators.required]],
    // votos_cand_425:['',[Validators.required]],
    // votos_cand_426:['',[Validators.required]],
    // votos_cand_427:['',[Validators.required]],
    // votos_cand_428:['',[Validators.required]],
    // votos_cand_429:['',[Validators.required]],
    // votos_cand_430:['',[Validators.required]],
    // votos_cand_431:['',[Validators.required]],
    // votos_cand_432:['',[Validators.required]],
    // votos_cand_433:['',[Validators.required]],
    // votos_cand_434:['',[Validators.required]],
    // votos_cand_435:['',[Validators.required]],
    // votos_cand_436:['',[Validators.required]],
    // votos_cand_437:['',[Validators.required]],
    // votos_cand_438:['',[Validators.required]],
    // votos_cand_439:['',[Validators.required]],
    // votos_cand_440:['',[Validators.required]],
    // votos_cand_441:['',[Validators.required]],
    // votos_cand_442:['',[Validators.required]],
    // votos_cand_443:['',[Validators.required]],
    // votos_cand_444:['',[Validators.required]],
    // votos_cand_445:['',[Validators.required]],
    // votos_cand_446:['',[Validators.required]],
    // votos_cand_447:['',[Validators.required]],
    // votos_cand_448:['',[Validators.required]],
    // votos_cand_449:['',[Validators.required]],
    // votos_cand_450:['',[Validators.required]],
    // votos_cand_451:['',[Validators.required]],
    // votos_cand_452:['',[Validators.required]],
    // votos_cand_453:['',[Validators.required]],
    // votos_cand_454:['',[Validators.required]],
    // votos_cand_455:['',[Validators.required]],
    // votos_cand_456:['',[Validators.required]],
    // votos_cand_457:['',[Validators.required]],
    // votos_cand_458:['',[Validators.required]],
    // votos_cand_459:['',[Validators.required]],
    // votos_cand_460:['',[Validators.required]],
    // votos_cand_461:['',[Validators.required]],
    // votos_cand_462:['',[Validators.required]],
    // votos_cand_463:['',[Validators.required]],
    // votos_cand_464:['',[Validators.required]],
    // votos_cand_465:['',[Validators.required]],
    // votos_cand_466:['',[Validators.required]],
    // votos_cand_467:['',[Validators.required]],
    // votos_cand_468:['',[Validators.required]],
    // votos_cand_469:['',[Validators.required]],
    // votos_cand_470:['',[Validators.required]],
    // votos_cand_471:['',[Validators.required]],
    // votos_cand_472:['',[Validators.required]],
    // votos_cand_473:['',[Validators.required]],
    // votos_cand_474:['',[Validators.required]],
    // votos_cand_475:['',[Validators.required]],
    // votos_cand_476:['',[Validators.required]],
    // votos_cand_477:['',[Validators.required]],
    // votos_cand_478:['',[Validators.required]],
    // votos_cand_479:['',[Validators.required]],
    // votos_cand_480:['',[Validators.required]],
    // votos_cand_481:['',[Validators.required]],
    // votos_cand_482:['',[Validators.required]],
    // votos_cand_483:['',[Validators.required]],
    // votos_cand_484:['',[Validators.required]],
    // votos_cand_485:['',[Validators.required]],
    // votos_cand_486:['',[Validators.required]],
    // votos_cand_487:['',[Validators.required]],
    // votos_cand_488:['',[Validators.required]],
    // votos_cand_489:['',[Validators.required]],
    // votos_cand_490:['',[Validators.required]],
    // votos_cand_491:['',[Validators.required]],
    // votos_cand_492:['',[Validators.required]],
    // votos_cand_493:['',[Validators.required]],
    // votos_cand_494:['',[Validators.required]],
    // votos_cand_495:['',[Validators.required]],
    // votos_cand_496:['',[Validators.required]],
    // votos_cand_497:['',[Validators.required]],
    // votos_cand_498:['',[Validators.required]],
    // votos_cand_499:['',[Validators.required]],
    // votos_cand_500:['',[Validators.required]],
  // });

  get tipo_eleccion() {
    return +this.selectForm.get('id_tipo_eleccion')?.value!  }

  ngOnInit(): void {
  }

  soloNumeros(event:any){
    let charCode = event.charCode ? event.charCode : event.keyCode;

    if(charCode != 8 && charCode != 9) {
      let max = 3;

      if((charCode < 48 || charCode > 57) || (event.target.value.length >= max)) return false
    }
    return;
  }

  bloquear(event:KeyboardEvent) {
    if(event.key === 'ArrowUp' || event.key === 'ArrowDown') {
      event.preventDefault();
    }
  }

  enter(event:any, id:string) {
    let keyCode = event.keyCode;

    if(keyCode == 13) {
      $(`#${id}`).focus();
    }
  }

  getTipoEleccion() {
    console.log(this.selectForm.get('id_tipo_eleccion')?.value)
  }

  registVotos():void {
  }

  isValidField(field:string) {
    return this.validatorsService.isValidField(this.selectForm,field);
  }

  getFieldErrors(field:string) {
    return this.validatorsService.getFieldErrors(this.selectForm,field);
  }
}
